@ATON_APIQuest_HostAddress = https://localhost:44356

POST {{ATON_APIQuest_HostAddress}}/api/users
Content-Type: application/json
{
  "login": "Admin",
  "password": "Admin123",
  "name": "System Administrator",
  "gender": 1,
  "birthday": null,
  "isAdmin": true,
  "createdBy": "System"
}
###

@id=e4c7a441-fdb0-49ae-995b-3633b236af65
PUT {{ATON_APIQuest_HostAddress}}/api/users/{{id}}
Content-Type: application/json
{
    "login": "Admin",
    "password": "Admin123",
    "name": "System Administrator",
    "gender": 1,
    "birthday": null,
    "admin": true,
    "createdOn": "2025-05-13T12:28:28.5082906Z",
    "createdBy": "System",
    "modifiedOn": null,
    "modifiedBy": null,
    "revokedOn": null,
    "revokedBy": null,
    "isActive": true
}
###

DELETE {{ATON_APIQuest_HostAddress}}/api/users/{{id}}

###


###

@adminLogin=Admin
@adminPassword=Admin123
POST {{ATON_APIQuest_HostAddress}}/api/Users?adminLogin={{adminLogin}}&adminPassword={{adminPassword}}
Content-Type: application/json
{
  "login": "user1",
  "password": "pass123",
  "name": "John Doe",
  "gender": 1,
  "birthday": "1990-01-01",
  "isAdmin": false,
  "createdBy": "Admin"
}

###
